### ISSUE TITLE
Move repo to the @Arabidopsis-Information-Portal organization

### ISSUE THREAD

**Issue by vivekkrish** [Arabidopsis-Information-Portal/atted-displayer#1]
Hi @joshkh, I was wondering if you wouldn't mind moving your atted-displayer repo to the AIP GitHub organization page? I have just sent you an invite to join the organization and be part of our ThaleMine development team.

Thank you!

**Comment by joshkh** [comment]
Can do, @vivekkrish! I accepted the invitation to join the Arabidopsis-Information-Portal organization, however not being an admin in the organization prevents me from transfering my repo to it.

According to Github:

> Only users with admin or owner access to an organization's repository can transfer the repository out of the organization. On the other end, the person transferring the repository also needs to have admin rights in the receiving organization.

I can transfer it directly to you, /vivekkrish, and then you can transfer it to /Arabidopsis-Information-Portal. Or you can make me a temporary admin. Either way works for me.

**Comment by vivekkrish** [comment]
Just added you as an admin. Please go ahead with the move the repo at your convenience.
Thank you!

**Comment by joshkh** [comment]
Sorry for the delay, @vivekkrish. I've transferred ownership to /Arabidopsis-Information-Portal

**Comment by vivekkrish** [comment]
Thank you @joshkh. Closing issue!
